FROM node:18

ARG API_URL
ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET
ARG AUTH_SECRET
ARG AUTH_TRUST_HOST
ARG MONGODB_URI

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
ENV API_URL ${API_URL}
ENV AUTH_GOOGLE_ID ${AUTH_GOOGLE_ID}
ENV AUTH_GOOGLE_SECRET ${AUTH_GOOGLE_SECRET}
ENV AUTH_SECRET ${AUTH_SECRET}
ENV AUTH_TRUST_HOST ${AUTH_TRUST_HOST}
ENV MONGODB_URI ${MONGODB_URI}
RUN npm run build
CMD npm run dev