name: Build & Publish Docker Image

on:
  push:
    branches:
      - RorryKelly-patch-1

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Secrets
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        if: DOCKER_USERNAME != null
        run: echo "$DOCKER_USERNAME"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build --build-arg API_URL=${{ secrets.API_URL }} --build-arg AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }} --build-arg AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}  --build-arg AUTH_SECRET=${{ secrets.AUTH_SECRET }} -build-arg AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }} --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} -t remoteflow .
          docker tag remoteflow ${{ secrets.DOCKER_USERNAME }}/remoteflow:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/remoteflow:latest

          docker build --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} -t remoteflow-chat ./chat-server
          docker tag remoteflow ${{ secrets.DOCKER_USERNAME }}/remoteflow-chat:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/remoteflow-chat:latest

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker image to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/remoteflow:latest
          docker stop $(docker ps -a -q) || true
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/remoteflow:latest

          docker pull ${{ secrets.DOCKER_USERNAME }}/remoteflow-chat:latest
          docker run -d -p 1324:1324 ${{ secrets.DOCKER_USERNAME }}/remoteflow-chat:latest
          EOF